repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.10
        args: ["--line-length=110"]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # Run pytest as a local hook using Poetry
  - repo: local
    hooks:
      - id: pytest-local
        name: pytest
        entry: poetry run pytest
        language: system
        types: [python]
        args: ['--timeout=10']
        pass_filenames: false
